apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-catalogservicedb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-catalogservicedb
  template:
    metadata:
      labels:
        app: mssql-catalogservicedb
    spec:
      containers:
        - name: mssql-catalogservicedb
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: catalogapidb-secret
                key: SA_PASSWORD
          volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: mssql-catalogservicedb
      volumes:
      - name: mssql-catalogservicedb
        persistentVolumeClaim:
          claimName: mssql-claim-catalogdb
---
apiVersion: v1
kind: Service
metadata:
  name: mssqlcatalogdb-clusterip-svc
spec:
  type: ClusterIP
  selector:
    app: mssql-catalogservicedb
  ports:
  - name: mssql-catalogservicedb
    protocol: TCP
    port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssqlcatalogdb-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mssql-catalogservicedb
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433